"use client";

import { useState } from "react";
import { useWeb3 } from "@/context/Web3Context";
import { getAssetSwapPolicy } from "@/lib/contracts";
import styles from "./AuditInteractionsWidget.module.css";

interface DecisionReport {
  id: string;
  proposalId: number;
  rationale: string;
  timeframe: string;
  ticketReceipt: string;
  timestamp: string;
}

interface AuditInteractionsWidgetProps {
  policyAddress: string;
  proposalsWithReports: DecisionReport[];
}

export default function AuditInteractionsWidget({ policyAddress, proposalsWithReports }: AuditInteractionsWidgetProps) {
  const { signer } = useWeb3();
  const [selectedReport, setSelectedReport] = useState<DecisionReport | null>(null);
  const [disputeStatus, setDisputeStatus] = useState<"idle" | "submitting" | "success" | "error">("idle");
  const [errorMsg, setErrorMsg] = useState("");

  const handleDispute = async (proposalId: number) => {
    if (!signer) return;
    setDisputeStatus("submitting");
    setErrorMsg("");

    try {
      const policy = getAssetSwapPolicy(policyAddress, signer);
      
      // triggerDispute(uint256 proposalId)
      const tx = await policy.triggerDispute(proposalId);
      await tx.wait();
      
      // In production: submit dispute details to API /api/audit/report
      
      setDisputeStatus("success");
      setTimeout(() => setDisputeStatus("idle"), 5000);
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || "Failed to trigger dispute.");
      setDisputeStatus("error");
    }
  };

  return (
    <div className={`glass-card ${styles.container}`}>
      <div className={styles.header}>
        <h3>Audit & Dispute</h3>
        <span className="badge badge-warning">Transparency Mode</span>
      </div>
      <p className={styles.subtitle}>
        Review verifiable decision reports generated by the AI Governor on the 0G network.
        Flag malicious or out-of-policy proposals to pause execution.
      </p>

      <div className={styles.content}>
        <div className={styles.reportList}>
          <h4>Recent Decision Reports</h4>
          {proposalsWithReports.length === 0 ? (
            <p className={styles.emptyText}>No AI generated proposals found.</p>
          ) : (
            <div className={styles.list}>
              {proposalsWithReports.map((report) => (
                <div 
                  key={report.id} 
                  className={`${styles.reportCard} ${selectedReport?.id === report.id ? styles.selected : ''}`}
                  onClick={() => setSelectedReport(report)}
                >
                  <div className={styles.cardHeader}>
                    <span className={styles.proposalId}>Proposal #{report.proposalId}</span>
                    <span className={styles.timestamp}>{report.timestamp}</span>
                  </div>
                  <div className={styles.ticketReceipt}>
                    Ticket: {report.ticketReceipt.slice(0, 10)}…{report.ticketReceipt.slice(-6)}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className={styles.reportDetail}>
          {selectedReport ? (
            <div className={styles.detailCard}>
              <div className={styles.detailHeader}>
                <h4>Report Details — #{selectedReport.proposalId}</h4>
              </div>
              
              <div className={styles.detailSection}>
                <h5>Agent Rationale</h5>
                <p className={styles.rationaleText}>{selectedReport.rationale}</p>
              </div>

              <div className={styles.detailSection}>
                <h5>Execution Timeframe</h5>
                <p className={styles.monoText}>{selectedReport.timeframe}</p>
              </div>

              <div className={styles.detailSection}>
                <h5>0G Network Verification</h5>
                <div className={styles.verificationBox}>
                  <div className={styles.verifiedIcon}>✓</div>
                  <div>
                    <span style={{ display: "block", fontSize: 12, fontWeight: 600 }}>Verifiable Ticket Receipt</span>
                    <span className={styles.monoText} style={{ wordBreak: "break-all" }}>
                      {selectedReport.ticketReceipt}
                    </span>
                  </div>
                </div>
              </div>

              <div className={styles.disputeAction}>
                <h5 style={{ color: "var(--accent-rose-light)" }}>Report Violation</h5>
                <p className={styles.hintText}>
                  If this proposal violates the treasury goals or risk limits, you can trigger an on-chain dispute to pause its execution. Requires {'>'}1% share balance.
                </p>
                
                {disputeStatus === "error" && (
                  <div className="alert alert-danger" style={{ marginBottom: 12 }}>
                    <span>⚠️ {errorMsg}</span>
                  </div>
                )}
                
                {disputeStatus === "success" ? (
                  <div className="alert alert-success">
                    <span>✅ Dispute registered. Proposal execution is paused for review.</span>
                  </div>
                ) : (
                  <button 
                    className="btn btn-danger" 
                    onClick={() => handleDispute(selectedReport.proposalId)}
                    disabled={disputeStatus === "submitting"}
                  >
                    {disputeStatus === "submitting" ? "Triggering..." : "Trigger On-Chain Dispute"}
                  </button>
                )}
              </div>
            </div>
          ) : (
            <div className={styles.emptyDetail}>
              <div style={{ fontSize: "3rem", opacity: 0.5, marginBottom: 16 }}>📄</div>
              <p>Select a decision report to view its rationale and audit trail.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
